spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/file_integrity_db
spring.datasource.username=root
spring.datasource.password=asritha@5306

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true